"""Generate a portable academic site. Edit content/site.json to maintain publications."""
from pathlib import Path
import json,html,re,urllib.parse
R=Path(__file__).parent; D=R/'dist'; data=json.loads((R/'content/site.json').read_text()); pubs=data['publications']
def e(s):return html.escape(str(s),quote=True)
def clean(s):return str(s).replace('**','')
def authors(p,full=False):
 a=[clean(x) for x in p['authors']]
 if len(a)>9 and not full:
  a=a[:3]+(['PsychENCODE Consortium'] if any('psychencode' in x.lower() for x in a[3:]) else [])+['et al.']
 return ', '.join('<strong>'+e(x)+'</strong>' if x=='Ziheng Duan' else e(x) for x in a)
def links(p):
 return '<div class="resource-links">'+''.join(f'<button class="text-link" data-cite="{e(x["url"])}">Cite</button>' if x['label']=='Cite' else f'<a href="{e(x["url"])}"'+(' target="_blank" rel="noopener"' if x['url'].startswith('http') or x['label']=='PDF' else '')+f'>{e(x["label"])} <span aria-hidden="true">↗</span></a>' for x in p['links'])+'</div>'
def row(p):
 return f'<article class="paper" data-year="{p["year"]}" data-type="{e(p["type"])}" data-search="{e(clean(p["title"]+" "+p["venue"]+" "+" ".join(p["authors"])).lower())}"><div class="paper-year">{p["year"]}</div><div><p class="venue">{e(p["venue"] or p["type"])}</p><h3><a href="{e(p["path"])}">{e(p["title"])}</a></h3><p class="authors">{authors(p)}</p>{links(p)}</div></article>'
HEADER='''<a class="skip" href="#main">Skip to content</a><header class="site-header"><div class="header-inner"><a class="brand" href="/" aria-label="Ziheng Duan homepage"><span class="monogram">ZD</span><span>Ziheng Duan</span></a><nav aria-label="Main navigation"><a href="/#news">News</a><a href="/#research">Research</a><a href="/#publication">Publications</a><a href="/#talks">Talks</a><a href="/#service">Service</a><a href="/#contact">Contact</a></nav><div class="header-tools"><button class="icon-button" id="search-open" aria-label="Search website"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg></button><button class="icon-button" id="theme-toggle" aria-label="Switch to dark mode" aria-pressed="false"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M20.5 14A8.8 8.8 0 0 1 10 3.5 8.8 8.8 0 1 0 20.5 14Z"/></svg></button><button class="menu-toggle" aria-controls="mobile-nav" aria-expanded="false">Menu</button></div></div><nav id="mobile-nav" aria-label="Mobile navigation" hidden><a href="/#news">News</a><a href="/#research">Research</a><a href="/#publication">Publications</a><a href="/#talks">Talks</a><a href="/#service">Service</a><a href="/#contact">Contact</a></nav></header>'''
FOOTER='''<footer><a class="brand" href="/">Ziheng Duan</a><span>© 2026 Ziheng Duan</span><a href="#top">Back to top ↑</a></footer><dialog id="search-dialog" aria-labelledby="search-heading"><div class="dialog-top"><h2 id="search-heading">Search</h2><button data-close aria-label="Close search">✕</button></div><label class="sr-only" for="site-search">Search publications, talks and pages</label><input id="site-search" type="search" placeholder="Search publications, talks, research…" autocomplete="off"><div id="search-results" aria-live="polite"></div></dialog><dialog id="cite-dialog" aria-labelledby="cite-heading"><div class="dialog-top"><h2 id="cite-heading">Citation</h2><button data-close aria-label="Close citation">✕</button></div><pre id="citation-text"></pre><div class="dialog-actions"><button class="button" id="copy-citation">Copy BibTeX</button><a class="button secondary" id="download-citation" download="citation.bib">Download .bib</a></div><p id="cite-status" role="status"></p></dialog><script src="/assets/app.js" defer></script>'''
def shell(title,body,description='Ziheng Duan — computational methods for single-cell gene regulation, spatial transcriptomics, and drug discovery.'):
 return '<!doctype html><html lang="en" id="top"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="'+e(description)+'"><meta name="color-scheme" content="light dark"><meta property="og:image" content="https://zihengduan.cn/media/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_512x512_fill_lanczos_center_2.png"><meta name="twitter:image" content="https://zihengduan.cn/media/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_512x512_fill_lanczos_center_2.png"><title>'+e(title)+'</title><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/style.css"><script>try{const t=localStorage.getItem("theme");if(t==="dark"||(!t&&matchMedia("(prefers-color-scheme: dark)").matches))document.documentElement.dataset.theme="dark"}catch{}</script></head><body>'+HEADER+body+FOOTER+'</body></html>'
def save(path,text):
 p=D/urllib.parse.unquote(path.lstrip('/'))/'index.html';p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text)
intro='''<main id="main"><section class="hero wrap" id="about"><div class="hero-copy"><p class="eyebrow">Artificial Intelligence &amp; Computational Biology</p><h1>Ziheng <span>Duan</span></h1><p class="position">Postdoctoral researcher <span>·</span> <a href="https://www.yale.edu/">Yale University</a></p><p class="lab-affiliation"><a href="https://www.gersteinlab.org/">Prof. Mark Gerstein’s lab</a></p><p class="hero-description">I develop trustworthy computational methods to understand <strong>single-cell gene regulation</strong>, particularly in spatial contexts, and translate these insights into disease understanding and drug discovery.</p><div class="social-links"><a href="https://scholar.google.com/citations?user=wA93e-kAAAAJ" target="_blank" rel="noopener">Google Scholar ↗</a><a href="https://github.com/RRRussell" target="_blank" rel="noopener">GitHub ↗</a><a href="mailto:duanziheng1206@gmail.com">Email ↗</a></div></div><figure class="portrait"><img src="/assets/portrait.jpg" alt="Ziheng Duan by the ocean" width="1600" height="1600" fetchpriority="high"></figure></section><div class="education wrap"><p>I earned my Ph.D. in Computer Science at <a href="https://uci.edu/">UC Irvine</a>, advised by <a href="https://www.ics.uci.edu/~jingz31/">Prof. Jing Zhang</a>. My research connects single-cell genomics and spatial transcriptomics with therapeutic target discovery. I also work with <a href="https://genesis.ml/" target="_blank" rel="noopener">Genesis Molecular AI</a> in computational biology.</p><div><span class="eyebrow">Education</span><p>Ph.D. · Computer Science<br><span class="muted">UC Irvine, 2025</span></p><p>B.S. · Zhejiang University<br><span class="muted">2020</span></p></div></div><section id="research" class="research-band"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">01 / Research</p><h2>From genes to<br>cellular landscapes.</h2></div><p>Learning how cells regulate, communicate,<br>and change in disease.</p></div><div class="research-grid"><article><span class="research-number">01</span><h3>Gene regulation</h3><p>Learning regulatory networks and chromatin organization from single-cell transcriptomic and epigenetic data.</p><a href="/publication/?q=scENCORE">scENCORE</a><a href="/publication/?q=iHerd">iHerd</a></article><article><span class="research-number">02</span><h3>Spatial Transcriptomics</h3><p>Joint analysis across tissue slices and modeling intercellular gene regulation from spatial transcriptomics.</p><a href="/publication/conference/muse/">MUSE</a><a href="/publication/?q=iMIRACLE">iMIRACLE</a></article><article><span class="research-number">03</span><h3>Disease &amp; discovery</h3><p>Identifying disease-associated network changes and prioritizing genes for therapeutic investigation.</p><a href="/publication/?q=PTSD">PTSD atlas</a></article></div></div></section>'''
industry_rows = ''.join('<article><p class="experience-date">'+e(x['dates'])+'</p><h3>'+e(x['role'])+'</h3><p>'+('<a href="'+e(x['company_url'])+'" target="_blank" rel="noopener">'+e(x['company'])+'</a>' if x.get('company_url') else e(x['company']))+' <span>'+e(x['team'])+'</span></p></article>' for x in data.get('industry', []))
industry_section = '<section id="experience" class="wrap industry-section" aria-labelledby="industry-heading"><div><p class="eyebrow">Industry</p><h2 id="industry-heading">Experience</h2></div><div class="industry-roles">'+industry_rows+'</div></section>'
intro = intro.replace('<section id="research"', industry_section+'<section id="research"', 1)
news_rows = ''.join('<li><time datetime="'+e(n['date'])+'">'+e(n['label'])+'</time><p>'+e(n['text'])+(' <a href="'+e(n['url'])+'">'+e(n['link_text'])+' ↗</a>' if n.get('url') else '')+'</p></li>' for n in data.get('news', []))
news_section = '<section id="news" class="wrap news-section" aria-labelledby="news-heading"><div><p class="eyebrow">Latest updates</p><h2 id="news-heading">News</h2></div><ul class="news-list">'+news_rows+'</ul></section>'
intro = intro.replace('<section id="research"', news_section+'<section id="research"', 1)
selected='''<section class="wrap section" id="publication"><div class="section-heading"><div><p class="eyebrow">02 / Publications</p><h2>Selected work</h2></div><a class="underlined" href="/publication/">All publications ↗</a></div><div class="papers">'''+''.join(row(p) for p in pubs if p['selected'])+'</div></section>'
def talk_context(t):
 parts=[t.get('event',''),t.get('date_label',''),t.get('location','')]
 return '<p class="talk-context">'+e(' · '.join(x for x in parts if x))+'</p>' if any(parts) else ''
def talk_row(t):
 badge='<span class="upcoming" data-event-date="'+e(t['date'])+'">Upcoming</span>' if t.get('upcoming') else ''
 return '<article class="talk"><div class="paper-year">'+str(t['year'])+'</div><div>'+badge+'<h3><a href="'+e(t['path'])+'">'+e(t['title'])+'</a></h3>'+talk_context(t)+('<p>'+e(t['summary'].replace('Present ','Presenting ').replace('a computationally method','a computational method'))+'</p>' if not t.get('event') else '')+links(t)+'</div></article>'
talksection='<section class="wrap section" id="talks"><div class="section-heading"><div><p class="eyebrow">03 / Talks</p><h2>Talks &amp; presentations</h2></div></div><div class="talk-list">'+''.join(talk_row(t) for t in data['talks'])+'</div></section>'

mentoring = data['mentoring']
mentoring_section = '<article class="mentoring-service"><h3>'+e(mentoring['program'])+'</h3><p>'+e(mentoring['role'])+'</p><ul>'+''.join('<li><span class="muted">'+str(p['year'])+'</span> · <a href="'+e(p['url'])+'" target="_blank" rel="noopener"><strong>'+e(p['name'])+'</strong></a> — '+e(p['description'])+'</li>' for p in mentoring['projects'])+'</ul></article>'
service='''<section class="wrap section" id="service"><div class="section-heading"><div><p class="eyebrow">04 / Service</p><h2>Academic community</h2></div></div><div class="service-grid"><article><h3>Teaching</h3><p>Reader · UC Irvine</p><ul><li>ICS 178 · Machine Learning and Data Mining<br><span class="muted">Winter &amp; Fall 2021</span></li><li>ICS 6D · Discrete Mathematics for Computer Science<br><span class="muted">Spring 2022</span></li></ul></article><article><h3>Reviewing</h3><p>AIMHC 2024 · PC member / reviewer</p><p class="muted">Selected journals</p><p>IEEE TPAMI · Information Science · Pattern Recognition · Pattern Recognition Letters · Knowledge-Based Systems · Knowledge and Information Systems · Neurocomputing</p><details><summary>More journals</summary><p>IEEE Access · Supercomputing · Reliability Engineering &amp; System Safety · Gene · Heliyon</p></details></article></div></section>'''
service = service.replace('<div class="service-grid">', '<div class="service-grid">'+mentoring_section, 1)
contact='''<section id="contact" class="contact-band"><div class="wrap contact-grid"><div><p class="eyebrow">05 / Contact</p><h2>Let’s connect.</h2><a class="email-link" href="mailto:duanziheng1206@gmail.com">duanziheng1206@gmail.com ↗</a><div class="social-links"><a href="https://www.linkedin.com/in/zihengduan" target="_blank" rel="noopener">LinkedIn ↗</a><a href="https://twitter.com/Ziheng1206" target="_blank" rel="noopener">X / Twitter ↗</a></div></div><form id="contact-form"><label for="contact-name">Your name</label><input id="contact-name" name="name" autocomplete="name" required><label for="contact-email">Your email</label><input id="contact-email" type="email" name="email" autocomplete="email" required><label for="contact-message">Message</label><textarea id="contact-message" name="message" rows="3" required></textarea><button class="button" type="submit">Open email draft ↗</button><p class="form-note">Opens your email app with your message ready to send.</p></form></div></section></main>'''
save('/',shell('Ziheng Duan · Computational Biology',intro+selected+talksection+service+contact))
years=sorted(set(p['year'] for p in pubs),reverse=True)
filters='<div class="filters"><div class="query"><label for="publication-query">Search publications</label><input type="search" id="publication-query" placeholder="Title, author, keyword…"></div><div><label for="publication-year">Year</label><select id="publication-year"><option value="">All years</option>'+''.join(f'<option>{y}</option>' for y in years)+'</select></div><div><label for="publication-type">Type</label><select id="publication-type"><option value="">All types</option><option>Journal article</option><option>Conference paper</option><option>Preprint</option></select></div></div>'
save('/publication/',shell('Publications · Ziheng Duan','<main id="main" class="wrap page"><p class="eyebrow">Research archive</p><h1 class="page-title">Publications<span>.</span></h1>'+filters+f'<p id="publication-count" class="muted" role="status">{len(pubs)} publications</p><div class="papers" id="publication-list">'+''.join(row(p) for p in pubs)+'</div><div id="no-results" hidden><h2>No matching publications</h2><p>Try another keyword or clear the filters.</p><button class="button" id="clear-filters">Clear filters</button></div></main>'))
for p in pubs:
 body='<main id="main" class="wrap detail page"><a class="back" href="/publication/">← Publications</a><p class="eyebrow">'+e(str(p['year'])+' / '+p['type'])+'</p><h1>'+e(p['title'])+'</h1><p class="detail-authors">'+authors(p,True)+'</p><p class="venue">'+e(p['venue'])+'</p>'+links(p)+('<section class="abstract"><h2>Abstract</h2><p>'+e(p['abstract'])+'</p></section>' if p['abstract'] else '')+'</main>'
 save(p['path'],shell(p['title']+' · Ziheng Duan',body,p['abstract'][:200]))
for t in data['talks']:
 save(t['path'],shell(t['title']+' · Ziheng Duan','<main id="main" class="wrap detail page"><a class="back" href="/#talks">← Talks</a><p class="eyebrow">'+str(t['year'])+' / Talk</p><h1>'+e(t['title'])+'</h1>'+talk_context(t)+'<p class="abstract">'+e(t['summary'])+'</p>'+links(t)+'</main>'))
# Preserve historic blog URLs and text without adding them to primary navigation.
for b in data['blogs']:
 save(b['relpermalink'],shell(b['title']+' · Ziheng Duan','<main id="main" class="wrap detail page"><a class="back" href="/">← Home</a><h1>'+e(b['title'])+'</h1><div class="legacy-text">'+e(b['content'])+'</div></main>'))
(D/'404.html').write_text(shell('Page not found · Ziheng Duan','<main id="main" class="wrap page"><p class="eyebrow">404</p><h1 class="page-title">Page not found.</h1><p>This page may have moved.</p><a class="button" href="/">Return home</a></main>'))
(D/'assets/content.json').write_text(json.dumps({'publications':pubs,'talks':data['talks']},ensure_ascii=False))
print('Generated homepage, publication archive,',len(pubs),'publication pages,',len(data['talks']),'talk pages, and',len(data['blogs']),'legacy pages.')
